// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTaskLogs(arg1) {
  return window['go']['main']['App']['ClearTaskLogs'](arg1);
}

export function DeleteOldTaskLogs(arg1) {
  return window['go']['main']['App']['DeleteOldTaskLogs'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function EnsureLogDirectory() {
  return window['go']['main']['App']['EnsureLogDirectory']();
}

export function ExecuteCardPackage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['ExecuteCardPackage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function ExecuteCardPackageWithContext(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['ExecuteCardPackageWithContext'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function ExecuteTask(arg1) {
  return window['go']['main']['App']['ExecuteTask'](arg1);
}

export function ExportTasks(arg1) {
  return window['go']['main']['App']['ExportTasks'](arg1);
}

export function ExportTasksByIDs(arg1, arg2) {
  return window['go']['main']['App']['ExportTasksByIDs'](arg1, arg2);
}

export function ExportTasksByTags(arg1, arg2) {
  return window['go']['main']['App']['ExportTasksByTags'](arg1, arg2);
}

export function GenerateTaskID() {
  return window['go']['main']['App']['GenerateTaskID']();
}

export function GetAllTasks(arg1, arg2) {
  return window['go']['main']['App']['GetAllTasks'](arg1, arg2);
}

export function GetTaskByID(arg1) {
  return window['go']['main']['App']['GetTaskByID'](arg1);
}

export function GetTaskProgress(arg1) {
  return window['go']['main']['App']['GetTaskProgress'](arg1);
}

export function GetTotalLogs(arg1) {
  return window['go']['main']['App']['GetTotalLogs'](arg1);
}

export function GetTotalTasks() {
  return window['go']['main']['App']['GetTotalTasks']();
}

export function ImportTasks(arg1) {
  return window['go']['main']['App']['ImportTasks'](arg1);
}

export function LoadTaskLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadTaskLogs'](arg1, arg2, arg3);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenSaveFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenSaveFileDialog'](arg1, arg2, arg3);
}

export function SaveTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['main']['App']['SaveTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function SaveTaskLogs(arg1) {
  return window['go']['main']['App']['SaveTaskLogs'](arg1);
}

export function SendRequest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function TestTask(arg1) {
  return window['go']['main']['App']['TestTask'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
}
