// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function ClearTaskLogs(arg1:string):Promise<void>;

export function DeleteOldTaskLogs(arg1:number):Promise<main.DeleteLogsResult>;

export function DeleteTask(arg1:string):Promise<string>;

export function EnsureLogDirectory():Promise<void>;

export function ExecuteCardPackage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:number,arg8:number,arg9:number,arg10:number):Promise<string>;

export function ExecuteCardPackageWithContext(arg1:context.Context,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:number,arg9:number,arg10:number,arg11:number,arg12:main.TaskProgress):Promise<string>;

export function ExecuteTask(arg1:string):Promise<string>;

export function ExportTasks(arg1:string):Promise<string>;

export function ExportTasksByIDs(arg1:string,arg2:Array<string>):Promise<string>;

export function ExportTasksByTags(arg1:string,arg2:Array<string>):Promise<string>;

export function GenerateTaskID():Promise<string>;

export function GetAllTasks(arg1:number,arg2:number):Promise<Record<string, main.Task>>;

export function GetTaskByID(arg1:string):Promise<main.Task>;

export function GetTaskProgress(arg1:string):Promise<main.TaskProgress>;

export function GetTotalLogs(arg1:string):Promise<number>;

export function GetTotalTasks():Promise<number>;

export function ImportTasks(arg1:string):Promise<string>;

export function LoadTaskLogs(arg1:string,arg2:number,arg3:number):Promise<main.TaskLogsResult>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function OpenSaveFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:number,arg9:number,arg10:string,arg11:string,arg12:number,arg13:number,arg14:Array<string>):Promise<string>;

export function SaveTaskLogs(arg1:main.TaskLogs):Promise<main.TaskLogsResult>;

export function SendRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function StopTask(arg1:string):Promise<string>;

export function TestTask(arg1:string):Promise<string>;

export function UpdateTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:number,arg10:number,arg11:string,arg12:string,arg13:number,arg14:number,arg15:Array<string>):Promise<string>;
