// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearTaskLogs(arg1:string):Promise<string>;

export function DeleteEnvVariable(arg1:string):Promise<string>;

export function DeleteTask(arg1:string):Promise<string>;

export function ExecuteTask(arg1:string):Promise<string>;

export function GetEnvVariables():Promise<Record<string, string>>;

export function GetEnvVariablesWithSeparator():Promise<Record<string, main.EnvVariableData>>;

export function GetExecutionLog(arg1:string):Promise<main.ExecutionLog>;

export function GetScheduledTasks():Promise<Array<string>>;

export function GetTaskCount():Promise<number>;

export function GetTaskLogEntries(arg1:string):Promise<Array<main.TaskLogEntry>>;

export function GetTaskLogs(arg1:string):Promise<Array<string>>;

export function GetTaskProgress(arg1:string):Promise<main.TaskProgress>;

export function GetTaskScheduleInfo(arg1:string):Promise<main.TaskScheduleInfo>;

export function GetTasks(arg1:number,arg2:number):Promise<main.TaskList>;

export function PreviewTaskWithVariables(arg1:string):Promise<Record<string, any>>;

export function SaveTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:number,arg10:Array<string>,arg11:string,arg12:main.SuccessCondition):Promise<string>;

export function ScheduleTask(arg1:string):Promise<string>;

export function SetEnvVariable(arg1:string,arg2:string):Promise<string>;

export function SetEnvVariableWithSeparator(arg1:string,arg2:string):Promise<string>;

export function StopTask(arg1:string):Promise<string>;

export function TestTask(arg1:string):Promise<string>;

export function TestTaskDataWithBackend(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:main.SuccessCondition):Promise<main.TestTaskResult>;

export function TestTaskWithBackend(arg1:string):Promise<main.TestTaskResult>;

export function UnscheduleTask(arg1:string):Promise<string>;

export function UpdateEnvVariable(arg1:string,arg2:string):Promise<string>;

export function UpdateEnvVariableWithSeparator(arg1:string,arg2:string):Promise<string>;

export function UpdateTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number,arg9:number,arg10:number,arg11:Array<string>,arg12:string,arg13:main.SuccessCondition):Promise<string>;
