// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTaskLogs(arg1) {
  return window['go']['main']['App']['ClearTaskLogs'](arg1);
}

export function DeleteEnvVariable(arg1) {
  return window['go']['main']['App']['DeleteEnvVariable'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function ExecuteTask(arg1) {
  return window['go']['main']['App']['ExecuteTask'](arg1);
}

export function GetEnvVariables() {
  return window['go']['main']['App']['GetEnvVariables']();
}

export function GetEnvVariablesWithSeparator() {
  return window['go']['main']['App']['GetEnvVariablesWithSeparator']();
}

export function GetExecutionLog(arg1) {
  return window['go']['main']['App']['GetExecutionLog'](arg1);
}

export function GetScheduledTasks() {
  return window['go']['main']['App']['GetScheduledTasks']();
}

export function GetTaskCount() {
  return window['go']['main']['App']['GetTaskCount']();
}

export function GetTaskLogEntries(arg1) {
  return window['go']['main']['App']['GetTaskLogEntries'](arg1);
}

export function GetTaskLogs(arg1) {
  return window['go']['main']['App']['GetTaskLogs'](arg1);
}

export function GetTaskProgress(arg1) {
  return window['go']['main']['App']['GetTaskProgress'](arg1);
}

export function GetTaskScheduleInfo(arg1) {
  return window['go']['main']['App']['GetTaskScheduleInfo'](arg1);
}

export function GetTasks(arg1, arg2) {
  return window['go']['main']['App']['GetTasks'](arg1, arg2);
}

export function PreviewTaskWithVariables(arg1) {
  return window['go']['main']['App']['PreviewTaskWithVariables'](arg1);
}

export function SaveTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['SaveTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function ScheduleTask(arg1) {
  return window['go']['main']['App']['ScheduleTask'](arg1);
}

export function SetEnvVariable(arg1, arg2) {
  return window['go']['main']['App']['SetEnvVariable'](arg1, arg2);
}

export function SetEnvVariableWithSeparator(arg1, arg2) {
  return window['go']['main']['App']['SetEnvVariableWithSeparator'](arg1, arg2);
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function TestTask(arg1) {
  return window['go']['main']['App']['TestTask'](arg1);
}

export function TestTaskDataWithBackend(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TestTaskDataWithBackend'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestTaskWithBackend(arg1) {
  return window['go']['main']['App']['TestTaskWithBackend'](arg1);
}

export function UnscheduleTask(arg1) {
  return window['go']['main']['App']['UnscheduleTask'](arg1);
}

export function UpdateEnvVariable(arg1, arg2) {
  return window['go']['main']['App']['UpdateEnvVariable'](arg1, arg2);
}

export function UpdateEnvVariableWithSeparator(arg1, arg2) {
  return window['go']['main']['App']['UpdateEnvVariableWithSeparator'](arg1, arg2);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}
